apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  labels:
    app: blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: kaushal2118/blog-app
          ports:
            - containerPort: 3000

